sudo: false
language: node_js
node_js:
  - "stable"
  - "5.1"
  - "5.0"
before_script:
  - npm install -g gulp
script: gulp test
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libvips-dev
      - g++-4.8
before_script: cat /home/travis/build/TenetPartners/tenet-holiday-card-2015/npm-debug.log
